/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.6.0.83.4 */
/* Module Version: 6.5 */
/* C:\lscc\diamond\3.6_x64\ispfpga\bin\nt64\scuba.exe -w -n RAM_06b_08b_DP -lang verilog -synth lse -bus_exp 7 -bb -arch ep5c00 -type bram -wp 10 -rp 0011 -rdata_width 6 -data_width 6 -num_rows 256 -cascade 11  */
/* Thu Mar 24 19:48:39 2016 */


`timescale 1 ns / 1 ps
module RAM_06b_08b_DP (WrAddress, RdAddress, Data, WE, RdClock, 
    RdClockEn, Reset, WrClock, WrClockEn, Q)/* synthesis NGD_DRC_MASK=1 */;
    input wire [7:0] WrAddress;
    input wire [7:0] RdAddress;
    input wire [5:0] Data;
    input wire WE;
    input wire RdClock;
    input wire RdClockEn;
    input wire Reset;
    input wire WrClock;
    input wire WrClockEn;
    output wire [5:0] Q;

    wire scuba_vhi;
    wire scuba_vlo;

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam RAM_06b_08b_DP_0_0_0_0.CSDECODE_B = "0b000" ;
    defparam RAM_06b_08b_DP_0_0_0_0.CSDECODE_A = "0b000" ;
    defparam RAM_06b_08b_DP_0_0_0_0.WRITEMODE_B = "NORMAL" ;
    defparam RAM_06b_08b_DP_0_0_0_0.WRITEMODE_A = "NORMAL" ;
    defparam RAM_06b_08b_DP_0_0_0_0.GSR = "DISABLED" ;
    defparam RAM_06b_08b_DP_0_0_0_0.REGMODE_B = "NOREG" ;
    defparam RAM_06b_08b_DP_0_0_0_0.REGMODE_A = "NOREG" ;
    defparam RAM_06b_08b_DP_0_0_0_0.DATA_WIDTH_B = 9 ;
    defparam RAM_06b_08b_DP_0_0_0_0.DATA_WIDTH_A = 9 ;
    DP16KC RAM_06b_08b_DP_0_0_0_0 (.DIA0(Data[0]), .DIA1(Data[1]), .DIA2(Data[2]), 
        .DIA3(Data[3]), .DIA4(Data[4]), .DIA5(Data[5]), .DIA6(scuba_vlo), 
        .DIA7(scuba_vlo), .DIA8(scuba_vlo), .DIA9(scuba_vlo), .DIA10(scuba_vlo), 
        .DIA11(scuba_vlo), .DIA12(scuba_vlo), .DIA13(scuba_vlo), .DIA14(scuba_vlo), 
        .DIA15(scuba_vlo), .DIA16(scuba_vlo), .DIA17(scuba_vlo), .ADA0(scuba_vlo), 
        .ADA1(scuba_vlo), .ADA2(scuba_vlo), .ADA3(WrAddress[0]), .ADA4(WrAddress[1]), 
        .ADA5(WrAddress[2]), .ADA6(WrAddress[3]), .ADA7(WrAddress[4]), .ADA8(WrAddress[5]), 
        .ADA9(WrAddress[6]), .ADA10(WrAddress[7]), .ADA11(scuba_vlo), .ADA12(scuba_vlo), 
        .ADA13(scuba_vlo), .CEA(WrClockEn), .CLKA(WrClock), .OCEA(WrClockEn), 
        .WEA(WE), .CSA0(scuba_vlo), .CSA1(scuba_vlo), .CSA2(scuba_vlo), 
        .RSTA(Reset), .DIB0(scuba_vlo), .DIB1(scuba_vlo), .DIB2(scuba_vlo), 
        .DIB3(scuba_vlo), .DIB4(scuba_vlo), .DIB5(scuba_vlo), .DIB6(scuba_vlo), 
        .DIB7(scuba_vlo), .DIB8(scuba_vlo), .DIB9(scuba_vlo), .DIB10(scuba_vlo), 
        .DIB11(scuba_vlo), .DIB12(scuba_vlo), .DIB13(scuba_vlo), .DIB14(scuba_vlo), 
        .DIB15(scuba_vlo), .DIB16(scuba_vlo), .DIB17(scuba_vlo), .ADB0(scuba_vlo), 
        .ADB1(scuba_vlo), .ADB2(scuba_vlo), .ADB3(RdAddress[0]), .ADB4(RdAddress[1]), 
        .ADB5(RdAddress[2]), .ADB6(RdAddress[3]), .ADB7(RdAddress[4]), .ADB8(RdAddress[5]), 
        .ADB9(RdAddress[6]), .ADB10(RdAddress[7]), .ADB11(scuba_vlo), .ADB12(scuba_vlo), 
        .ADB13(scuba_vlo), .CEB(RdClockEn), .CLKB(RdClock), .OCEB(RdClockEn), 
        .WEB(scuba_vlo), .CSB0(scuba_vlo), .CSB1(scuba_vlo), .CSB2(scuba_vlo), 
        .RSTB(Reset), .DOA0(), .DOA1(), .DOA2(), .DOA3(), .DOA4(), .DOA5(), 
        .DOA6(), .DOA7(), .DOA8(), .DOA9(), .DOA10(), .DOA11(), .DOA12(), 
        .DOA13(), .DOA14(), .DOA15(), .DOA16(), .DOA17(), .DOB0(Q[0]), .DOB1(Q[1]), 
        .DOB2(Q[2]), .DOB3(Q[3]), .DOB4(Q[4]), .DOB5(Q[5]), .DOB6(), .DOB7(), 
        .DOB8(), .DOB9(), .DOB10(), .DOB11(), .DOB12(), .DOB13(), .DOB14(), 
        .DOB15(), .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="RAM_06b_08b_DP.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;



    // exemplar begin
    // exemplar attribute RAM_06b_08b_DP_0_0_0_0 MEM_LPC_FILE RAM_06b_08b_DP.lpc
    // exemplar attribute RAM_06b_08b_DP_0_0_0_0 MEM_INIT_FILE 
    // exemplar attribute RAM_06b_08b_DP_0_0_0_0 RESETMODE SYNC
    // exemplar end

endmodule
