-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.9.0.99.2
-- Module  Version: 5.7
-- Sun Sep 10 16:53:47 2017

-- parameterized module component declaration
component pll_60
    port (CLKI: in  std_logic; RST: in  std_logic; CLKOP: out  std_logic; 
        LOCK: out  std_logic);
end component;

-- parameterized module component instance
__ : pll_60
    port map (CLKI=>__, RST=>__, CLKOP=>__, LOCK=>__);
